apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dcastrog111/fullstack-api-app-backend:latest
        ports:
        - containerPort: 8080
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: PG_HOST
            value: "postgres"
          - name: PG_DATABASE
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: PG_DATABASE
          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: PG_USER
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: PG_PASSWORD
          - name: ConnectionStrings__DefaultConnection
            value: "Host=postgres;Port=5432;Username=admin;Password=secret;Database=backdb"