apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: dcastrog111/fullstack-api-app-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: "http://backend:8080"