apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app-demo
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort